# Generated by Django 4.1.4 on 2023-01-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_recommandlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsubscribe',
            options={'verbose_name': '그룹 구독', 'verbose_name_plural': '그룹 구독'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AlterModelOptions(
            name='publishgrouphistory',
            options={'verbose_name': '이메일 전송 내역(그룹)', 'verbose_name_plural': '이메일 전송 내역(그룹)'},
        ),
        migrations.AlterModelOptions(
            name='publishmemberhistory',
            options={'verbose_name': '이메일 전송 내역(멤버)', 'verbose_name_plural': '이메일 전송 내역(멤버)'},
        ),
        migrations.AlterModelOptions(
            name='recommandlink',
            options={'verbose_name': '추천 링크 목록', 'verbose_name_plural': '추천 링크 목록'},
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=36, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='recommandlink',
            name='hit',
            field=models.IntegerField(verbose_name='hit'),
        ),
        migrations.AlterField(
            model_name='recommandlink',
            name='sub_domain',
            field=models.CharField(max_length=36, verbose_name='sub domain'),
        ),
        migrations.AlterField(
            model_name='recommandlink',
            name='top_level_domain',
            field=models.CharField(max_length=36, verbose_name='top level domain'),
        ),
    ]
