# Generated by Django 4.1.4 on 2022-12-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_emailhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailhistory',
            name='date_of_create',
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='date_of_resend',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='date_of_send',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
