# Generated by Django 4.1.4 on 2022-12-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_emailhistory_date_of_create_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailhistory',
            table='email_history',
        ),
    ]
